# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rogeriorslf <rogeriorslf@student.42.fr>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/11 05:54:15 by rogeriorslf       #+#    #+#              #
#    Updated: 2021/06/11 07:35:45 by rogeriorslf      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: make
	gcc -Wall -Werror -Wextra -g *.c libft/libft.a

make:
	cd libft; make; make clean
